name: Freebuild
main: com.mcmiddleearth.freebuild.Freebuild
version: 0.1
description: Freebuild controler
commands:
  theme:
    description: new plot(s)
    usage: |
            /theme new
            /theme set
            /theme
permissions:
  plotmanager.create:
    default: op
    children:
        plotmanager.build: true
  plotmanager.build:
    default: true
    